data:
  data_location: ./data
  extension: wav
  mean_loudness: -12.019168884523456
  std_loudness: 1.1228461400155099
export:
  out_dir: ./export
  realtime: true
mfcc:
  fft_sizes: 1024
  mel_bins: 64
  mfcc_bins: 3
model:
  block_size: 512
  hidden_size: 512
  n_bands: 65
  n_harmonic: 100
  sampling_rate: 48000
preprocess:
  block_size: 512
  oneshot: false
  out_dir: ./preprocess
  sampling_rate: 48000
  signal_length: 192000
train:
  batch_size: 16
  decay: 24000
  eval_steps: 100
  learning_rate_start: 0.001
  learning_rate_stop: 0.0001
  model_name: latent_flute
  out_dir: ./train
  overlap: 0.75
  scales:
  - 4096
  - 2048
  - 1024
  - 512
  - 256
  - 128
  steps: 30000
