data:
  data_location: ./data
  extension: wav
  mean_loudness: -3.602290232976278
  std_loudness: 1.9615751107533772
model:
  block_size: 256
  hidden_size: 512
  n_bands: 65
  n_harmonic: 100
  sampling_rate: 48000
preprocess:
  block_size: 256
  oneshot: false
  out_dir: ./preprocessed/
  sampling_rate: 48000
  signal_length: 192000
train:
  overlap: 0.75
  scales:
  - 4096
  - 2048
  - 1024
  - 512
  - 256
  - 128
