data:
  data_location: ./data/doublebass
  extension: wav
  mean_loudness: -11.986202430725097
  std_loudness: 0.9611788809299469
export:
  out_dir: ./export
  realtime: true
model:
  block_size: 512
  hidden_size: 512
  n_bands: 65
  n_harmonic: 100
  sampling_rate: 48000
preprocess:
  block_size: 512
  oneshot: false
  out_dir: ./preprocess
  sampling_rate: 48000
  signal_length: 192000
train:
  batch_size: 16
  decay: 400000
  eval_steps: 100
  learning_rate_start: 0.001
  learning_rate_stop: 0.0001
  model_name: control_doublebass
  out_dir: ./train
  overlap: 0.75
  scales:
  - 4096
  - 2048
  - 1024
  - 512
  - 256
  - 128
  steps: 500000
