data:
  data_location: ./data
  extension: wav
  mean_loudness: -10.715228716532389
  std_loudness: 1.4954177339871724
model:
  block_size: 512
  hidden_size: 512
  n_bands: 65
  n_harmonic: 100
  sampling_rate: 48000
preprocess:
  block_size: 512
  oneshot: false
  out_dir: ./preprocessed/training_220512
  sampling_rate: 48000
  signal_length: 192000
train:
  overlap: 0.75
  scales:
  - 4096
  - 2048
  - 1024
  - 512
  - 256
  - 128
